import { useEffect,useState } from 'react';
import { router } from 'expo-router';
import * as Linking from 'expo-linking';
import { H1,Input,Paragraph,Separator,Spinner,Text,XStack,YStack } from 'tamagui';
import { XButton } from '../../src/components/XButton';
import { supabase } from '../../src/lib/supabase';
function readAuthParams(url:string){const fragment=url.includes('#')?url.slice(url.indexOf('#')+1):'';const query=url.includes('?')?url.slice(url.indexOf('?')+1).split('#')[0]:'';const params=new URLSearchParams(fragment||query);return{code:params.get('code'),access_token:params.get('access_token'),refresh_token:params.get('refresh_token'),error:params.get('error_description')??params.get('error')};}
export default function RestoreScreen(){const[ready,setReady]=useState(false);const[password,setPassword]=useState('');const[confirmPassword,setConfirmPassword]=useState('');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[error,setError]=useState('');
useEffect(()=>{let mounted=true;async function prepare(url?:string){try{const target=url??await Linking.getInitialURL();if(target&&supabase){const auth=readAuthParams(target);if(auth.error)throw new Error(auth.error);if(auth.code){const{error:exchangeError}=await supabase.auth.exchangeCodeForSession(auth.code);if(exchangeError)throw exchangeError;}else if(auth.access_token&&auth.refresh_token){const{error:sessionError}=await supabase.auth.setSession({access_token:auth.access_token,refresh_token:auth.refresh_token});if(sessionError)throw sessionError;}}if(mounted)setReady(true);}catch(e){if(mounted){setError(e instanceof Error?e.message:'Unable to restore the secure authentication session.');setReady(true);}}}void prepare();const subscription=Linking.addEventListener('url',event=>{void prepare(event.url);});return()=>{mounted=false;subscription.remove();};},[]);
async function updatePassword(){if(!supabase||!password||busy)return;if(password.length<6){setError('Password must be at least 6 characters.');return;}if(password!==confirmPassword){setError('Passwords do not match.');return;}setBusy(true);setError('');setMessage('');try{const{error:updateError}=await supabase.auth.updateUser({password});if(updateError)throw updateError;setMessage('Password updated. You can continue to X-App.');}catch(e){setError(e instanceof Error?e.message:'Unable to update password.');}finally{setBusy(false);}}
if(!ready)return <YStack flex={1} bg="$background" p="$5" items="center" justify="center"><YStack items="center" gap="$3"><XStack bg="$brandSoft" px="$3" py="$2" rounded="$10"><Text color="$brandBackground" fontSize="$2" fontWeight="900" letterSpacing={1}>X-APP</Text></XStack><Spinner color="$brandBackground"/><Text color="$colorPress">Restoring secure session…</Text></YStack></YStack>;
return <YStack flex={1} bg="$background" p="$5" items="center" justify="center"><YStack width="100%" maxW={520} gap="$5"><YStack gap="$3"><XStack bg="$brandSoft" px="$3" py="$2" rounded="$10" self="flex-start"><Text color="$brandBackground" fontSize="$2" fontWeight="900" letterSpacing={1}>X-APP</Text></XStack><YStack gap="$2"><H1 fontSize="$10" fontWeight="900">Choose a new password.</H1><Paragraph color="$colorPress" size="$4">Set a new password for your account.</Paragraph></YStack></YStack><YStack gap="$3"><Text fontSize="$5" fontWeight="800">Secure recovery</Text><Paragraph color="$colorPress">Choose a new password to finish account recovery.</Paragraph><Input secureTextEntry placeholder="New password" value={password} onChangeText={setPassword}/><Input secureTextEntry placeholder="Confirm new password" value={confirmPassword} onChangeText={setConfirmPassword} onSubmitEditing={()=>{void updatePassword();}}/>{error?<Paragraph color="$error">{error}</Paragraph>:null}{message?<Paragraph color="$success">{message}</Paragraph>:null}<XButton onPress={()=>{void updatePassword();}} disabled={busy||!password||!confirmPassword}>{busy?'Updating…':'Update password'}</XButton></YStack><YStack gap="$3" items="center"><Separator width="100%" borderColor="$borderColor"/><XButton chromeless onPress={()=>router.replace('/(auth)/sign-in')}>Back to sign in</XButton></YStack></YStack></YStack>;}
